import type { Metadata } from 'next';
import './styles/globals.scss';
import { Suspense } from 'react';
import Loading from './loading';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Suspense fallback={<Loading />}>
					<header className="header">
						<Navbar />
					</header>
					{children}
				</Suspense>
			</body>
		</html>
	);
}
